<a href="https://colab.research.google.com/github/Mparate1234/Py_stat_DS_ML/blob/main/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Statement1: 
Write a Python program to multiply a 5×3 matrix by 3×2 matrix and create a real matrix product.


In [1]:
import numpy as np

In [2]:
a=np.arange(5,20).reshape(5,3)
b=np.arange(8,14).reshape(3,2)
print(a)
print("------------------")
print(b)
print("------------------")
print(np.dot(a,b))

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
------------------
[[ 8  9]
 [10 11]
 [12 13]]
------------------
[[184 202]
 [274 301]
 [364 400]
 [454 499]
 [544 598]]


# Problem Statement2:
Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only

In [3]:
import numpy as np
p=np.array(['Python','PHP','JS','Examples','html5',5])
Digits_only=[]
Lower_cases_only=[]
Upper_cases_only=[]
for i in p:
    a=i.isdigit()
    Digits_only.append(a)
    b=i.islower()
    Lower_cases_only.append(b)
    c=i.isupper()
    Upper_cases_only.append(c)
print("Digits_only",Digits_only)
print("Lower_cases_only",Lower_cases_only)
print("Upper_cases_only",Upper_cases_only)



Digits_only [False, False, False, False, False, True]
Lower_cases_only [False, False, False, False, True, False]
Upper_cases_only [False, True, True, False, False, False]


# Problem Statement3: 

Write a program thatreads two space-separated positive integers X and Yas input and perform the following tasks:
Tasks to be performed:
 1.Create a list (lst1) starting at one (1) with 16 elements at a step of X
 2.Create a list (lst2) starting at one (1) with 16 elements at a step of Y
 3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
 4.Reshape both the NumPy arrays to (4,4)
 5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
 6.Print all the elements of np3 in a single dimension list like the format as shown below:a.[n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [4]:
import numpy as np

a=list(range(1,32,2))
b=list(range(1,48,3))
np1=np.array(a)
np2=np.array(b)
print(np1)
print(np2)
np1=np.array(a).reshape(4,4)
np2=np.array(b).reshape(4,4)
print(np1)
print(np2)
np3=np1-np2
print(np3)
np.ravel(np3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]
[[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]
 [37 40 43 46]]
[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15])

# Problem Statement4: 
Write a Python program thattakes two integer-NumPy arrays, P and Q of shape [3*3] and performthe following task:
Task to be performed:
Print the element-wise difference of the matrix P and Q(P-Q)

In [5]:
import numpy as np
a=np.array([23,56,87,3,6,96,4,6,78]).reshape(3,3)
b=np.array([12,34,54,7,2,54,6,2,78]).reshape(3,3)
print(a-b)

[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
